website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from .models import Post, User ,Comment ,EditPostForm 
from . import db



views = Blueprint("views", __name__)


@views.route("/")
@views.route("/home")
@login_required
def home():
    posts = Post.query.all()
    return render_template("home.html", user=current_user, posts=posts)


@views.route("/ajouter_post", methods=['GET', 'POST'])
@login_required
def create_post():
    if request.method == "POST":
        text = request.form.get('text')

        if not text:
            flash('Post ne peut pas être vide ', category='error')
        else:
            post = Post(text=text, author=current_user.id)
            db.session.add(post)
            db.session.commit()
            flash('Post crée!', category='success')
            return redirect(url_for('views.home'))

    return render_template('ajouter_post.html', user=current_user)


@views.route("/delete-post/<id>")
@login_required
def delete_post(id):
    post = Post.query.filter_by(id=id).first() #check s'il ya un post qui a cet id

    if not post:
        flash("Post n'existe pas.", category='error')
    elif current_user.id == post.id: #si c'est le user qui a crée le post 
        flash("vous n'avez pas la pérmission pour supprimer ce post .", category='error')
    else:
        db.session.delete(post)
        db.session.commit()
        flash('Post supprimé.', category='success')

    return redirect(url_for('views.home'))


@views.route("/posts/<username>")
@login_required
def posts(username):
    user = User.query.filter_by(username=username).first()

    if not user:
        flash("il n'existe aucun utilisateur avec ce username ", category='error')
        return redirect(url_for('views.home'))

    posts = user.posts
    return render_template("posts.html", user=current_user, posts=posts, username=username)


@views.route('/posts')
@login_required
def posts_list():
    keyword = request.args.get('q')
    username = request.args.get('username')

    if keyword:
        posts = Post.query.filter(Post.text.ilike(f"%{keyword}%")).all()
        title = f'Les Posts avec "{keyword}"'
    elif username:
        user = User.query.filter_by(username=username).first()
        if not user:
            flash("Il n'existe aucun utilisateur avec cet username.", category='error')
            return redirect(url_for('views.home'))
        posts = user.posts
        title = f"Les Posts de {username}"
    else:
        posts = Post.query.all()
        title = "All Posts"

    return render_template('posts.html', posts=posts, title=title,user=current_user)



@views.route("/delete-profile/<int:user_id>", methods=['POST'])
@login_required
def delete_profile(user_id):
    if current_user.id == user_id:
        user = User.query.get(user_id)
        if user:
            #supprimer les posts du user 
            Post.query.filter_by(author=user_id).delete()
            
            # apès supprimer le user
            db.session.delete(user)
            db.session.commit()
            
            flash("votre compte et vos posts associés ont été bien supprimés.", category='success')
            return redirect(url_for('views.home'))
        else:
            flash("User n'existe pas.", category='error')
    else:
        flash("vous avez pas la permission de supprimer ce compte.", category='error')

    return redirect(url_for('views.home'))

@views.route("/create-comment/<post_id>", methods=['POST'])
@login_required
def create_comment(post_id):
    text = request.form.get('text')

    if not text:
        flash('Comment cannot be empty.', category='error')
    else:
        post = Post.query.filter_by(id=post_id)
        if post:
            comment = Comment(
                text=text, author=current_user.id, post_id=post_id)
            db.session.add(comment)
            db.session.commit()
        else:
            flash('Post does not exist.', category='error')

    return redirect(url_for('views.home'))



@views.route("/delete-comment/<int:comment_id>")
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get(comment_id)

    if not comment:
        flash('Comment does not exist.', category='error')
    elif current_user.id != comment.author and current_user.id != comment.post.author:
        flash('You do not have permission to delete this comment.', category='error')
    else:
        db.session.delete(comment)
        db.session.commit()

    return redirect(url_for('views.home'))

@views.route('/edit-post/<int:post_id>', methods=['GET', 'POST'])
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    form = EditPostForm()

    if form.validate_on_submit():
        post.text = form.text.data  
        db.session.commit()
        flash('Post mis à jour avec succès.', 'success')
        return redirect(url_for('views.edit_post', post_id=post.id))

    form.text.data = post.text  
    return render_template('edit_post.html', form=form, post=post, post_id=post_id, user=current_user)







website/templates/ajouter_post.html
{% extends "base.html" %} {% block title %}Home{% endblock %}
{% block content %}
<h1 align="center">Ajouter un Post</h1>
<form method="POST">
    <textarea name="text" id="text" class="form-control"></textarea>
    <br/>
    <div align="center">
        <button type="submit" class="btn btn-lg btn-primary">&nbsp;Post&nbsp;</button>
    </div>



</form>
<br  />
<div align="center"> 
    <a href="/home">
        <button type="button" class="btn btn-lg btn-primary">Retour</button>
    </a>

</div>








{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    
    <title>{% block title %}{% endblock %}</title>

</head>
<style>

  .btsearch{
    background-color: #4caf50 ;
    color: white;
  }
  body {
        padding-top: 55px; 
    }
</style>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar"> 
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav me-auto">
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="/home">Home</a>
                    <a class="nav-item nav-link" href="/logout">Logout</a>
                    <form method="GET" action="{{ url_for('views.posts_list') }}" class="d-flex">
                      <div class="input-group">
                          <input type="search" class="form-control rounded" placeholder="saisir mot-clé" aria-label="Search" aria-describedby="search-addon" name="q" />
                          <button type="submit" class="btn btn-outline-primary btsearch">Search</button>
                      </div>
                  </form>
                {% else %}
                    <a class="nav-item nav-link" href="/login">Login</a>
                    <a class="nav-item nav-link" href="/sign-up">Sign-up</a>
                {% endif %}
            </div>
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                
                    <form action="{{ url_for('views.delete_profile', user_id=current_user.id) }}" method="POST">
                        <button type="submit" class="btn btn-danger">
                            <i class="bi bi-trash"></i> Supprimer Profile
                        </button>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
</nav>





  {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
      {% for category, message in messages %}
        {% if category == "error" %}
          <div class="alert alert-danger alter-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
          </div>
        {% endif %}
    
        {% if category == "success" %}
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
          </div>
        {% endif %}
    
      {% endfor %}
    {% endif %}
  {% endwith %}

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>


</html>

website/templates/edit_post.html
{% extends "base.html" %}

{% block title %}Modifier le Post{% endblock %}

{% block content %}
<h1 align="center">Modifier le Post</h1>
<form method="POST">
    {{ form.csrf_token }}
    <div class="form-group">
        {{ form.text.label(class="form-label") }}
        {{ form.text(class="form-control") }}
    </div>
    <br/>
    <div align="center">
        <button type="submit" class="btn btn-lg btn-primary">Modifier</button>
    </div>
</form>
<br/>
<div align="center"> 
    <a href="/home">
        <button type="button" class="btn btn-lg btn-primary">Retour</button>
    </a>
</div>

{% endblock %}

website/templates/home.html
{% extends "posts_div.html" %} {% block title %}Home{% endblock %}

website/templates/login.html
{% extends "base.html"%}
{% block title %}Login{% endblock %}
{% block content %}
<style>
    .logform{
        border-radius: 10px;
        background-color: white;
        box-shadow: 2px;

    }
    
</style>
<div class="d-flex align-items-center justify-content-center" style="min-height: 70vh;">
    <div class="row">
        <div class="col-md-6">
            <form method="POST">
                <h3 align="center">Login</h3>
                <div class="form-group">
                    <label for="email">Email Address</label>
                    <input type="text" id="email" name="email" class="form-control" placeholder="Enter Email"/>
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" class="form-control" placeholder="Enter Password"/>
                    <br/>
                    <div align="center">
                        <button class="btn btn-outline-primary" type="submit">Login</button>
                    </div>
                    <br/>
                    <div class="text-center">
                        <p>Créer un nouveau compte <a href="/sign-up">Sign-up</a></p>
                    </div>
                </div>    
            </form>
        </div>
        <div class="col-md-6 d-flex align-items-center justify-content-center">
            <div>
                <h2>Avec notre plateforme,</h2>
                <h4>Partagez et restez en interaction avec la meilleure communauté .</h4>
            </div>
        </div>
    </div>
</div>



{% endblock %}


website/templates/posts.html
{% extends "posts_div.html" %}

{% block title %}
    {% if username %}
        Les Posts de {{ username }}
    {% elif keyword %}
        Les Posts avec "{{ keyword }}"
    {% else %}
        Tous les Posts
    {% endif %}
{% endblock %}

{% block header %}
    {% if username %}
        Les Posts de {{ username }}
    {% elif keyword %}
        Les Posts avec "{{ keyword }}"
    {% else %}
        Tous les Posts
    {% endif %}
{% endblock %}

{% block footer %}
    <div align="center">
        <a href="/home">
            <button type="button" class="btn btn-primary btn-lg">Retour</button>
        </a>
    </div>
{% endblock %}

website/templates/posts_div.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
  <h1 align="center">{% block header %}Posts{% endblock %}</h1>
  <style>
    .card-text {
      display: -webkit-box;
      -webkit-line-clamp: 3;
      -webkit-box-orient: vertical;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    .ajpost{
        background-color: #4caf50;
    }
    .username-link {
        text-decoration: none;
    }

    
  </style>
  <div id="posts">
    <div class="row">
        {% for post in posts %}
        <div class="col-md-4">
          <div class="card mb-4">
            <div class="card-header d-flex justify-content-between align-items-center">
              <a href="/posts/{{ post.user.username }}" class="username-link">
                <img src="{{ url_for('static', filename='image/person-circle.svg') }}" class="user-icon" style="width: 24px; height: 24px;">
                {{ post.user.username }}
              </a>
              {% if user.id == post.author %}
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-bs-toggle="dropdown">
                  Options
                </button>
                <ul class="dropdown-menu">
                  <li>
                    <a href="/delete-post/{{ post.id }}" class="dropdown-item">Supprimer</a>
                    <a href="{{ url_for('views.edit_post', post_id=post.id) }}" class="dropdown-item">Editer</a>
                  </li>
                </ul>
              </div>
              {% endif %}
            </div>
          <div class="card-body">
            <div class="card-text">{{post.text}}</div>
            <div class="collapse" id="comments-{{post.id}}">
                <div class="card">
                  <div class="card-body" id="comments-expanded-{{post.id}}">
                    {% for comment in post.comments %}
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <a href="/posts/{{comment.user.username}}"
                          >{{comment.user.username}}</a
                        >: {{comment.text}}
                      </div>
                      <div>
                        <small class="text-muted"> {{comment.date_created}}</small>
                        {% if user.id == comment.author or user.id == post.author %}
                        <div class="btn-group">
                          <button
                            type="button"
                            class="btn btn-sm btn-primary dropdown-toggle"
                            data-bs-toggle="dropdown"
                          ></button>
                          <ul class="dropdown-menu">
                            <li>
                              <a
                                href="/delete-comment/{{comment.id}}"
                                class="dropdown-item"
                                >Supprimer</a>
                            </li>
                          </ul>
                        </div>
                        {% endif %}
                      </div>
                    </div>
                    {% endfor %}
                  </div>
                </div>
              </div>
              <p class="card-text">
                {% if post.comments|length > 0 %}
                <a data-bs-toggle="collapse" href="#comments-{{post.id}}" role="button">
                  <small>Afficher {{post.comments|length}} Commentaires</small>
                </a>
                {% else %}
                <small class="text-muted">Aucun commentaire</small>
                {% endif %}
              </p>
              <form
                class="input-group mb-3"
                method="POST"
                action="/create-comment/{{post.id}}"
              >
                <input
                  type="text"
                  id="text"
                  name="text"
                  class="form-control"
                  placeholder="taper votre commentaire"
                />
                <button type="submit" class="btn btn-primary">Comment</button>
            </form>
          </div>
          <div class="card-footer text-muted">{{post.date_created}}</div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

  <div align="center">
    <a href="/ajouter_post" class="btn btn-primary btn-lg fixed ajpost">Ajouter un Post</a>
  </div>
{% endblock %}

website/templates/signup.html
{% extends "base.html"%}
{% block title %}HOME{% endblock %}
{% block content %}
<div class="d-flex align-items-center justify-content-center" style="min-height: 70vh;">
    <div class="row">
        <div class="col-md-6">
            <form method="POST">
                <h3 align="center">Sign Up</h3>
                <div class="form-group">
                    <label for="email">Email Address</label>
                    <input type="text" id="email" name="email" class="form-control" placeholder="Enter Email"/>

                    <label for="username">Username</label>
                    <input type="text" id="username" name="username" class="form-control" placeholder="Enter Username"/>

                    <label for="password1">Password</label>
                    <input type="password" id="password1" name="password1" class="form-control" placeholder="Enter Password"/>

                    <label for="password2">Confirm Password</label>
                    <input type="password" id="password2" name="password2" class="form-control" placeholder="Confirm Password"/>

                    <br/>
                    <div align="center">
                        <button class="btn btn-outline-primary" type="submit">Sign Up</button>
                    </div>
                    <br/>

                    <div class="text-center">
                        <p>Vous avez déjà un compte? <a href="/login">Login</a></p>
                    </div>
                </div>    
            </form>
        </div>
        <div class="col-md-6 d-flex align-items-center justify-content-center">
            <div>
                <h2>Partagez vos idées, vos réflexions</h2>
                <h4>et vos expériences avec une communauté passionnée.</h4>
            </div>
        </div>
    </div>
</div>


{% endblock %}